---
title: Op de eerste rij - Cultuureducatie
timezone: Europe/Amsterdam
collections:
  crew:
    title: Crew
    output: false
    author: info@opde1sterij.nl
    korte-beschrijving: De hele Op de eerste rij crew.
  posts:
    title: Posts
    output: true
    author: info@opde1sterij.nl
    korte-beschrijving: Elke maand een nieuwe blog van de Op de eerste rij crew.
    assets:
    - path: "/uploads/Elke%20maand%20een%20nieuwe%20blog.png"
      name: elke-maand-een-nieuwe-blog
    - path: "/uploads/blog.jpg"
      name: blog
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
    zoektermen: 
    korte-beschrijving: 
    trailer-embed-code: 
    filmpje-embed-code: 
    formulier-link: 
    home-page: 
    assets:
    - path: ''
      name: ''
- scope:
    path: ''
    type: posts
  values:
    layout: default
    permalink: "/blog/:i_day-:i_month-:year-:title/"
    blogger: 
    trailer-embed-code: 
    filmpje-embed-code: 
    formulier-link: 
    assets:
    - path: ''
      name: ''
- scope:
    path: ''
    type: crew
  values:
    onderdeel: 
    blogger-bio: 
    assets:
    - path: ''
      name: ''
repository: opde1sterij/archived
url: https://www.opde1sterij.nl
permalink: pretty
markdown: kramdown
auteur: Op de eerste rij
include:
- ".gearchiveerd"
- ".gearchiveerd-2"
- ".2021-03-10-7-mini-films.markdown"
- ".2021-11-03-alert-cjp-budget.markdown"
- ".2022-03"
- ".2022-04"
- ".2022-05"
- ".2022-06"
- ".2022-07"
- ".2022-09"
- ".2022-11"
- ".2022-12"
- ".2023-01"
- ".2023-02"
- ".2023-03"
- ".2023-04"
- ".2023-05"
- ".2023-06"
- ".2023-09"
- ".2023-11"
- ".2023-12"
- ".2024-01"
- ".2024-02"
- ".2024-03"
- ".2024-04"
- ".2024-april"
- ".2024-06"
- ".2024-07"
- ".2025-02"
plugins:
- jekyll-redirect-from
whitelist:
- jekyll-redirect-from
